MovieCollection/Controllers/MoviesController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieCollection.Models;
using PagedList;
using System.IO;
using Microsoft.AspNet.Identity;

namespace MovieCollection.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Movies
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.ReleaseDateSortParm = sortOrder == "ReleaseDate" ? "releaseDate_desc" : "ReleaseDate";
            ViewBag.CurrentUser= User.Identity.GetUserId();

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var movies = from s in db.Movies
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Title.Contains(searchString)
                                       || s.Description.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "title_desc":
                    movies = movies.OrderByDescending(s => s.Title);
                    break;
                case "ReleaseDate":
                    movies = movies.OrderBy(s => s.ReleaseDate);
                    break;
                case "releaseDate_desc":
                    movies = movies.OrderByDescending(s => s.ReleaseDate);
                    break;
                default: 
                    movies = movies.OrderBy(s => s.Title);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(movies.ToPagedList(pageNumber, pageSize));
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            else {
                ViewBag.CurrentUser = User.Identity.GetUserId();
            }           

            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieID,Title,Description,ReleaseDate,Director,Poster")] Movie movie, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                var fileName = upload !=null? Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName): String.Empty;
                var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);

                movie.Poster = fileName;
                var currentUserId = User.Identity.GetUserId();
                movie.User = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                db.Movies.Add(movie);
                db.SaveChanges();
                if (!String.IsNullOrEmpty(fileName))
                    upload.SaveAs(path);

                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null || 
                (movie.User != null && 
                    movie.User.Id != User.Identity.GetUserId())
                )
            {
                return HttpNotFound();
            }

            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Movie movie, HttpPostedFileBase upload)
        {
            if (movie.User != null && movie.User.Id != User.Identity.GetUserId())
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                var fileName = upload != null ? Guid.NewGuid().ToString() + Path.GetExtension(upload.FileName) : String.Empty;
                var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);

                var oldPoster = db.Movies.Find(movie.MovieID).Poster;
                if (!String.IsNullOrEmpty(oldPoster))
                {
                    var delpath = Path.Combine(Server.MapPath("~/Content/images"),oldPoster);
                    if (System.IO.File.Exists(delpath))
                    {
                        System.IO.File.Delete(delpath);
                    }
                }

                var movieInDb = db.Movies.Find(movie.MovieID);

                movie.Poster = fileName;

                db.Entry(movieInDb).CurrentValues.SetValues(movie);
                db.Entry(movieInDb).State = EntityState.Modified;
                
                db.SaveChanges();

                if (!String.IsNullOrEmpty(fileName))
                    upload.SaveAs(path);

                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null ||
                (movie.User != null &&
                    movie.User.Id != User.Identity.GetUserId())
                )
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);

            if (movie.User != null && movie.User.Id != User.Identity.GetUserId())
            {
                return HttpNotFound();
            }

            var delpath = Path.Combine(Server.MapPath("~/Content/images"), movie.Poster);
            if (System.IO.File.Exists(delpath))
            {
                System.IO.File.Delete(delpath);
            }

            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MovieCollection/Views/Movies/Create.cshtml
@model MovieCollection.Models.Movie

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/bootstrap")
    
@using (Html.BeginForm("Create", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
        @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 5 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control datecontrol" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Poster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Poster" name="upload" class="form-control-file" accept="image/jpeg,image/png,image/gif"/>
            </div>
        </div>    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {
        if (!Modernizr.inputtypes.date) {
            $(function () {
                $(".datecontrol").datetimepicker({
                    format: 'YYYY-MM-DD'
                });
            });
        }
    });
</script>    

MovieCollection/Views/Movies/Delete.cshtml
@model MovieCollection.Models.Movie

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Movie</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ReleaseDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Director)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Director)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Poster)
            </dt>
    
            <dd>
                <img src="@Url.Content("~/Content/images/"+ (String.IsNullOrEmpty(Model.Poster)? "blank.png":Model.Poster))" height="60" width="60">
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

MovieCollection/Views/Movies/Details.cshtml
@model MovieCollection.Models.Movie

<h4>Movie</h4>
<hr />
<div style="position: relative;">
    <div class="item">
        <div class="item_left">
            <div class="poster">
                <img src="@Url.Content("~/Content/images/"+ (String.IsNullOrEmpty(Model.Poster)? "blank.png":Model.Poster))" >
            </div>
        </div>

        <div class="item_right">
            <dl class="dl-horizontal details">
                <dt>
                    @Html.DisplayNameFor(model => model.Title):
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description):
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ReleaseDate):
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ReleaseDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Director):
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Director)
                </dd>
            </dl>
        </div>
    </div>
    <div class="clear"></div>
</div>
<div style="position: relative;">
    <p>
        @if (Model.User != null && ViewBag.CurrentUser == Model.User.Id)
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.MovieID })            
            @:|
        }
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

MovieCollection/Views/Movies/Edit.cshtml
@model MovieCollection.Models.Movie

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/bootstrap")
    
@using (Html.BeginForm("Edit", "Movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MovieID)
    
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Poster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content("~/Content/images/"+ (String.IsNullOrEmpty(Model.Poster)? "blank.png":Model.Poster))" height="60" width="60" class="e-preview">
                <input type="file" id="Poster" name="upload" class="form-control-file" accept="image/jpeg,image/png,image/gif" />
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(document).ready(function () {
        if (!Modernizr.inputtypes.date) {
            $(function () {
                $(".datecontrol").datetimepicker({
                    format: 'YYYY-MM-DD'
                });
            });
        }
    });
</script>

MovieCollection/Views/Movies/Index.cshtml
@model PagedList.IPagedList<MovieCollection.Models.Movie>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Movies";
}

<h2>Movies</h2>

<p>
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Create New", "Create")
}
else {
    <br/>
}
</p>
@using (Html.BeginForm("Index", "Movies", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
            <tr>
                <th class="col-lg-1">
                    @Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th class="col-lg-4">
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
                </th>
                <th class="col-lg-1">
                    @Html.ActionLink("Release Date", "Index", new { sortOrder = ViewBag.ReleaseDateSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th class="col-lg-1">
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Director)
                </th>
                <th class="col-lg-1">
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Poster)
                </th>
                <th class="col-lg-2"></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @(item.Description.Length > 100 ? item.Description.Substring(0, 100) + "..." : item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReleaseDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Director)
                    </td>
                    <td>
                        <img src="@Url.Content("~/Content/images/"+ (String.IsNullOrEmpty(item.Poster)? "blank.png":item.Poster))" height="50" width="50" alt="img poster">
                    </td>
                    <td>
                        @if (item.User != null && ViewBag.CurrentUser == item.User.Id )
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = item.MovieID })
                            @:|
                        }                      
                        @Html.ActionLink("Details", "Details", new { id = item.MovieID }) 
                        
                        @if (item.User != null && ViewBag.CurrentUser == item.User.Id)
                        {
                            @:|
                            @Html.ActionLink("Delete", "Delete", new { id = item.MovieID })
                        }
                        
                    </td>
                </tr>
            }

        </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))